# Project information
site_name: Taskbox
site_url: https://dongbox.github.io/taskbox/
site_author: Dongbox
site_description: >-
  The box allowed you to execute multi-process and manage complicated task well.

# Repository
repo_name: Dongbox/taskbox
repo_url: https://github.com/Dongbox/taskbox

# Copyright
copyright: Copyright &copy; 2024 Dongbox

# Configuration
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

# Page tree
nav:
  - Home: index.md
  - Getting started:
    - Installation: getting-started.md
    - License: license.md
  - Reference:
    - reference/index.md
    - Task: reference/task.md
    - TaskBox: reference/taskbox.md
    - 'Extra: Data Type': reference/data.md

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_bases: true
          show_source: false
          show_inheritance_diagram: true
          find_stubs_package: true
          heading_level: 2
          docstring_style: google
          docstring_section_style: table
          merge_init_into_class: false
          show_if_no_docstring: false
          show_docstring_functions: true
          show_docstring_classes: true
          show_docstring_examples: true
          show_docstring_other_parameters: true
          parameter_headings: true
          show_root_heading: true
          show_root_toc_entry: true
          show_root_members_full_path: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true

extra:
  version:
    provider: mike